# install multiple packages
---
- name: Win_chocolatey module demos
  hosts: all
  become: false
  gather_facts: false
 # - name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  loop:
  #- git
  #- putty
  #- notepadplusplus
   - googlechrome
   - procexp
 # vars:
   # - packages:
    #  - git
     # - notepadplusplus
 # tasks:
  #  - name: install packages
   #   chocolatey.chocolatey.Win_chocolatey:
    #    name: "{{ packages }}" 
     #   state: present

