---
- name: gather_facts from chocolatey
  hosts: win
  become: false
  gather_facts: false
  tasks:
    - name: Gather facts from chocolatey
      win_chocolatey_facts:

    - name: Displays the Configuration
      debug:
        var: ansible_chocolatey.config
   

    - name: Displays the Feature
      debug:
        var: ansible_chocolatey.feature
    - name: Gather all facts from chocolatey, except outdated packages
      win_chocolatey_facts:
        filter:
          - 'config'
          - 'feature'
          - 'packages'
          - 'sources'    
