---
- name: gather_facts from chocolatey
  hosts: win
  become: false
  gather_facts: false
  tasks:
    - name: Gather facts from chocolatey
      win_chocolatey_facts:

    - name: Displays the Configuration
      debug:
        var: ansible_chocolatey.config
   

