---
- name: create a windows user
  hosts: win
  tasks: 
    - name: create windows users
      win_user:
        name: fayo
        password: "Passw0rd!"
        state: absent
        groups: 
          - Users
