---
- name: Install Windows Updates
  hosts: answn
  gather_facts: false
  become_method: runas
  tasks:
    - name: Install all security updates 
      win_updates:
        reboot: false
        reboot_timeout: 3600


#- name: Install all security updates with automatic reboots
#  ansible.windows.win_updates:
 #   category_names:
  #  - SecurityUpdates
   # reboot: true        
