---
- name: Install all updates and reboot as many times as needed
  hosts: answn
  become: false
  gather_facts: false
  tasks:
    - name: Install all critical and updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups

        state: installed  
        reboot: yes
        reboot_timeout: 3600
        log_path: C:\ansible.txt





