---
- hosts: win
  become: false
  tasks:
    - name: Remove a file, if present
      win_file:
        path: C:\Temp\foo.conf
        state: absent

    - name: Remove directory structure
      win_file:
        path: C:\Temp
        state: absent
