---
- name: Install all updates
  hosts: all
  #become: false
  #gather_facts: false
  tasks:
    - name: Install all critical and updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        state: installed  
        reboot: true
        #reboot_timeout: 3600
        log_path: C:\ansible.txt

    #- name: reboot host if required
     # win_reboot:
      #when: update_result.reboot_required

