# Create a new issue and add a comment to it

#- vi globol_create.yaml

---
- name: Integrate Ansible with Jira
  hosts: localhost
  vars_files:
    - secrets.yaml
  vars:
    jirauri: "https://gafsad.atlassian.net"
  tasks:
    - name: Create a Jira issue
      community.general.jira:
        uri: '{{ jirauri }}'
        username: '{{ username }}'
        password: '{{ password }}'
        project: IP
        operation: create
        issuetype: Task
        summary: Ansible Integration Issue
    
