- name: My First Play
  hosts: all
  gather_facts: true 
  become: true
  tasks:
    - name: Ma First Task
      package:
        name: tree
        state: present
    - name: Print Progress
      debug:
        msg: "This is {{ ansible_distribution }}"
