# to set the issue in progress
---
- name: Integrate Ansible with Jira
  hosts: localhost
  vars_files:
    - secrets.yaml
  vars:
    jirauri: "https://gfstest.atlassian.net/"
  tasks:
    - name: Create a Jira issue
      community.general.jira:
        uri: '{{jirauri}}'
        username: '{{username}}'
        password: '{{password}}'
        project: PA
        operation: transition # set it to transition
        status: In Progress #set it to IP
        issue: PA-7
