---
- name: make me secure
  hosts: rocky
  tasks:
  - lineinfile:
      name: /etc/sudoers
      regexp: '^Defaults'
      line: 'Defaults timestamp_type=global,timestamp_timeout=60'
      validate: /usr/sbin/visudo -cf %s    

