## apt package on ubuntu servers 
---
- name: Install latest version of "openjdk-6-jdk" ignoring "install-recommends"
  hosts: ubuntu
  become: true
  tasks:
    - name: install openjdk-6jdk
      ansible.builtin.apt:
        name: openjdk-6-jdk
        state: latest
        install_recommends: no
