# install lamp on ubuntu server or setup a lamp server
---
- name: Ansible lamp server
  hosts: lampstack
  become: true
  tasks:
    - name: install multiple packages - Lamp
      register: updatesys
      apt:
        update_cache: true
        name:
          - firewalld
          - apache2
          - mariadb-server
          - php
          - php-mysql
        state: present   
    
