## apt package on ubuntu servers 
---
- name: Install latest version of "openjdk-17-jdk" ignoring "install-recommends"
  hosts: ubuntu
  become: true
  tasks:
    - name: Ansible install openjdk-17-jdk
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: latest
        install_recommends: no
