## apt package on ubuntu server 
---
- name: Install latest version of "openjdk-6-jdk" ignoring "install-recommends"
  hosts: ubuntu
  become: true
  tasks:
    ansible.builtin.apt:
    name: openjdk-6-jdk
    state: latest
    install_recommends: no
