---
- name: demonstrate failing tasks
  gather_facts: no
  hosts: all
  tasks:
  - name: creating users the wrong way
    user:
    name: lewis
  - debug:
      msg: run me again and see if you get here
