## This is when conditional where the application will be installed according to OS Version and
## when the requirement are met
---
- name: install start and enable httpd
  hosts: all
  tasks:
  - name: install package
    package:
      name: httpd
      state: present
    when: ansible_distribution == "Centos"
  - name: start and enable service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Centos"
  - name: open port in firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes
    when: ansible_distribution == "Centos"
  
  - name: install tree
    yum: name=tree state=present
    when: ansible_distribution == "Centos"

  - name: install apache2
    apt: name=apache2 state=present
    when: ansible_distribution == "Ubuntu"
  
  - name: install tree
    apt: name=tree state=present
    when: ansible_distribution == "Ubuntu"
# - name: test httpd accessibility
 #  become: false
  # gather_facts: no
   #hosts: localhosts
  # tasks:
  # - name: test httpd access
   #  uri:
    #    url: http://ansible2
    

