---
- name: install start and enable httpd
  hosts: ansubuntu
  tasks:
<<<<<<< HEAD
  - name: install apache
=======
  - name: install package
>>>>>>> 57898875972172af3ae94c8da5fd10d6f7aa59e3
    package:
      name: httpd
      state: present
  - name: start and enable service
    service:
      name: httpd
      state: started
      enabled: yes
  - name: open port in firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes
  - name: install apache httpd
    ansible.builtin.apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"
# - name: test httpd accessibility
 #  become: false
  # gather_facts: no
   #hosts: localhosts
  # tasks:
  # - name: test httpd access
   #  uri:
    #    url: http://ansible2
    
