---
- name: Install apache httpd  (state=present is optional)
  hosts: ansubuntu
  become: true
  gather_facts: false
  ansible.builtin.apt:
    name: apache2
    state: present
- name: Install latest version of "openjdk-6-jdk" ignoring "install-recommends"
  ansible.builtin.apt:
    name: openjdk-6-jdk
    state: latest
    install_recommends: no
when: "'{{ ansible_distribution }}'"a == "Ubuntu"
