

- name: copy files between hosts
  hosts: ansible2
  tasks:
  - name: copy file from ansubuntu to rocky
    copy:
      src: /etc/hosts
      dest: /tmp/hosts
      mode: "0644"
    delegate_to: ansible3
  - name: check file
    stat:
      path: /tmp/hosts
    register: stafile
  - debug:
      var: stafile
