# defined the label from ansible
---
- name: Integrate Ansible with Jira
  hosts: localhost
  vars_files:
    - secrets.yaml
  vars:
    jirauri: "https://gfstest.atlassian.net/"
  tasks:
    - name: Create a Jira issue
      community.general.jira:
        uri: '{{jirauri}}'
        username: '{{username}}'
        password: '{{password}}'
        project: PA
        operation: edit
        issue: PA-7
      args:
        fields:
          labels:
            - autocreated
