- name: 'Manage Apache Deployment'
  hosts: ansible2
  become: true
  gather_facts: false
  tasks:
      - name: 'Install Apache Web Server'
        package:
           name: 'httpd'
           state: 'present'

      - name: 'Ensure web server is running and enabled'
        service:
          name: 'httpd'
          state: 'started'
          enabled: true
      - name: 'Copy web content'
        copy:
          dest: '/var/www/html/'
          src: 'web/'

