---
- name: 'Manage User Account'
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: 'Delete User'
      user:
        name: "{{ user_account | default('ansible') }}"
        state: 'absent'
        remove: true
      when: user_create == 'no'  
