- name: 'Create and Manage Users'
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: 'Create a User Account'
      user:
        name: 'ansible'
        state: 'present'
        shell: '/bin/bash'

